### ISSUE TITLE
unreadable in dark mode

### ISSUE THREAD

**Issue by Schokokex** [apex/gh-polls#47]
github introduced darkmode,
if enabled, the poll labels are hard to read

**Comment by Schokokex** [comment]
easy to reproduce in the Readme, Dark mode can be enabled in your profile page

**Comment by mcornella** [comment]
Can confirm. I think adding a white background to [the exported `<svg>` would be enough](https://github.com/apex/gh-polls/blob/820156017c1e3de466a6efa5b078c2be9d692f67/internal/poll/poll_option.go#L14). At least the graphs would be readable.

EDIT: if you're using refined-github, this custom CSS works:
```css
.markdown-body img[data-canonical-src^="https://api.gh-polls.com/poll"] {
    background-color: #fff;
}
```
